modLoader = "neoforge"
loaderVersion = "[4,)"
license = "GPL-3.0-only"

[[mods]]
modId = "openlumin"
version = "${version}"
displayName = "OpenLumin"
description = "High-performance 2D/3D rendering library for Minecraft"
authors = "NDBlockConnect Team"

[[mixins]]
config = "openlumin.mixins.json"

[[dependencies.openlumin]]
    modId = "neoforge"
    type = "required"
    versionRange = "[26.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.openlumin]]
    modId = "minecraft"
    type = "required"
    versionRange = "[26.2,26.3)"
    ordering = "NONE"
    side = "BOTH"
