org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.51-beta

mod_id=openlumin
mod_name=OpenLumin
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=io.github.openlumin
