modLoader = "javafml"
loaderVersion = "[28,)"
license = "GPL-3.0-only"

[[mods]]
modId = "openlumin"
version = "${version}"
displayName = "OpenLumin"
description = "High-performance 2D/3D rendering library for Minecraft"
authors = "NDBlockConnect Team"

[[dependencies.openlumin]]
    modId = "forge"
    type = "required"
    versionRange = "[28,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.openlumin]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.14.4,1.14.5)"
    ordering = "NONE"
    side = "BOTH"
